Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"

    config.vm.network "private_network", ip: "10.0.0.1",
      virtualbox__intnet: "intranet", auto_config: false

    config.vm.network "private_network", ip: "10.0.1.1",
      virtualbox__intnet: "dmz", auto_config: false

    config.vm.network "private_network", ip: "1.2.3.4",
      virtualbox__intnet: "internet", auto_config: false

    config.vm.provision "file", source: "../SECRETS", destination: "/vagrant/SECRETS"
  
    config.vm.provision "shell", path: "scripts/startup_script.sh"
  end