Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"

    config.vm.network "private_network", ip: "10.0.0.3",
      virtualbox__intnet: "intranet"
  
    config.vm.provision "shell", path: "scripts/startup_script.sh"
  end
  