#!/bin/bash

# # interfaces(5) file used by ifup(8) and ifdown(8)
# # Include files from /etc/network/interfaces.d:
# source-directory /etc/network/interfaces.d

# # The loopback network interface
# auto lo
# iface lo inet loopback

# # The primary network interface
# allow-hotplug eth0
# iface eth0 inet dhcp
# #VAGRANT-BEGIN
# # The contents below are automatically generated by Vagrant. Do not modify.
# auto eth1
# iface eth1 inet static
#       address 10.0.0.3
#       netmask 255.255.255.0
#       gateway 10.0.0.1 # add this
# #VAGRANT-END
# # afterwards: sudo service networking restart

# auto eth1
# iface eth1 inet static
#     address 1.2.3.42
#     netmask 255.255.255.0
#     gateway 1.2.3.4


# ip route

# cleanup script, which we will run just before exporting the machines:

# unmount /vagrant
sudo umount /vagrant
echo "ls /vagrant: (should be empty line)"
echo $(ls /vagrant)

# set random root password instead of root:vagrant
root_passwd=$(openssl rand -base64 32)
echo "root:$root_passwd" | sudo chpasswd
echo "changed default root password"

# Go to sysadmin on user-gui

# delete vagrant network interface (eth0, 10.0.2.2)
sudo ifdown eth0
echo "disabled eth0 (vagrant) interface"

# delete vagrant user
sudo deluser --remove-home vagrant
id vagrant
echo "Deleted user vagrant"

# Reboot

# Check functionnality

# Delete history

# Shutdown machine
# sudo shutdown now

# Export .ova (SELECT ALL INTERFACES)

# Check functionnality

# For user-gui
# delete /vagrant entry in /etc/fstab