Vagrant.configure("2") do |config|
    config.vm.box = "chenhan/lubuntu-desktop-20.04"

    config.vm.provider "virtualbox" do |vb|
        # Display the VirtualBox GUI when booting the machine
        vb.gui = true
        vb.memory = "2048"
        vb.cpus = "2"
      end

    config.vm.network "private_network", ip: "1.2.3.42",
        virtualbox__intnet: "internet"

    config.trigger.before [:up, :provision] do |trigger|
      trigger.info = "Copying global secrets into local folder..."
      trigger.run = {path: "./scripts/copy_global_secrets.sh"}
    end

    config.vm.provision "shell", path: "scripts/startup_script.sh"
  end