Vagrant.configure("2") do |config|
    config.vm.box = "chenhan/lubuntu-desktop-20.04"

    config.vm.provider "virtualbox" do |vb|
        # Display the VirtualBox GUI when booting the machine
        vb.gui = true
        vb.memory = "2048"
        vb.cpus = "2"
      end

    config.vm.network "private_network", ip: "1.2.3.42",
        virtualbox__intnet: "internet"

    config.vm.provision "file", source: "../SECRETS", destination: "/vagrant/SECRETS"

    config.vm.provision "shell", path: "scripts/startup_script.sh"
  end